### ISSUE TITLE
Remove Version retention

### ISSUE THREAD

**Issue by GCP-ally** [cloudspannerecosystem/spanner-dump#14]
Unable to exclude version retention settings with DDL export. Is there a work-around for this? I'm unable to import Version Retention settings using spanner-cli.

**Comment by yfuruyama** [comment]
Thanks for reporting the issue. Now I opened the [PR](https://github.com/cloudspannerecosystem/spanner-cli/pull/116) in spanner-cli to fix this issue.

I'll update this again once original fix is resolved.

**Comment by GCP-ally** [comment]
Good Morning Yuki,

Thank you very much for looking into this!

**Comment by yfuruyama** [comment]
Now the fix is merged and [the new version](https://github.com/cloudspannerecosystem/spanner-cli/releases/tag/v0.9.7) is released.

I confirmed that exported DDL which has the version retention setting can be imported with the latest spanner-cli. I will close this issue, but please reopen this if you still see an issue with the latest spanner-cli.
